name: CI - BarberFlow Python TDD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    # 2. Configura o Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        # INDICA ONDE ESTÁ O ARQUIVO PARA O CACHE FUNCIONAR
        cache-dependency-path: barberflow-backend/requirements.txt

    # 3. Instala as dependências
    # CORREÇÃO AQUI: Entramos na pasta (cd) antes de instalar
    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        cd barberflow-backend
        pip install -r requirements.txt

    # 4. RODA OS TESTES
    # CORREÇÃO AQUI: O pytest roda dentro da pasta correta
    - name: Rodar Testes (TDD)
      working-directory: ./barberflow-backend
      run: pytest