name: CI - BarberFlow Python TDD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    # 2. Configura o Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: barberflow-backend/requirements.txt

    # 3. Instala as dependências (Pytest, Flask, etc.)
    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        # Entra na subpasta do Backend
        cd barberflow-backend
        # Instala libs do requirements.txt + pytest, caso não esteja lá
        pip install -r requirements.txt
        pip install pytest

    # 4. RODA OS TESTES (Ponto Crítico)
    - name: Rodar Testes (TDD)
      working-directory: ./barberflow-backend
      run: |
        # Configura a variável de ambiente para o Python encontrar a pasta 'app'
        export PYTHONPATH=$PYTHONPATH:.
        # Roda o Pytest com output detalhado
        pytest -v